### ISSUE TITLE
Iteration 1 Lessons Learned

### ISSUE THREAD

**Issue by laczech** [ThomasBassa/near-netcar#1]
Customer Feedback:
- We need a lost-link protocol, so that if the connection is lost, it'll at least stop moving.
- Needs to return when the link is restored.
- Identify bad port, troubleshoot.
- Robot needs to work at all times. 
- Need documentation for the Pi, manual.
- More failure mode testing (what happens when...).

If we're doing a demo for a customer, and something goes wrong, don't ever say that we don't know.

**Comment by ThomasBassa** [comment]
This is six issues and should be split as such...

**Comment by king-of-kong** [comment]
these are issues rather than lessons...

**Comment by king-of-kong** [comment]
I don't like that last sentence either

**Comment by ThomasBassa** [comment]
This is now correctly broken into other issues.
